// src/lib/rag/retriever.ts
// Vector similarity retrieval over cached embeddings.
// Uses cosine similarity. Supports metadata filtering by domain and symptomSystem.
// Falls back gracefully if embedding cache is not yet built.

import type { KnowledgeDomain, SymptomSystem } from "./knowledge-base";
import type { EmbeddedEntry } from "./embedder";

// ── Cache loading ────────────────────────────────────────────────────────────
// The embedding cache is a JSON file generated by /api/rag/ingest.
// We load it lazily and hold it in module-level memory for the process lifetime.

let _cache: EmbeddedEntry[] | null = null;
let _cacheLoadAttempted = false;

async function loadCache(): Promise<EmbeddedEntry[]> {
  if (_cache !== null) return _cache;
  if (_cacheLoadAttempted) return [];
  _cacheLoadAttempted = true;

  // Dynamic import so this file is safe in edge/browser environments
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require("fs") as typeof import("fs");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require("path") as typeof import("path");
    const cachePath = path.join(process.cwd(), "src", "lib", "rag", "embeddings-cache.json");
    if (!fs.existsSync(cachePath)) {
      console.warn("[RAG] embeddings-cache.json not found. Run POST /api/rag/ingest to build it.");
      return (_cache = []);
    }
    const raw = fs.readFileSync(cachePath, "utf-8");
    _cache = JSON.parse(raw) as EmbeddedEntry[];
    console.info(`[RAG] Loaded ${_cache.length} embedded entries from cache`);
    return _cache;
  } catch (err) {
    console.error("[RAG] Failed to load embeddings cache:", err);
    return (_cache = []);
  }
}

/** Invalidate the in-memory cache (call after /api/rag/ingest regenerates the file) */
export function invalidateCache(): void {
  _cache = null;
  _cacheLoadAttempted = false;
}

// ── Cosine similarity ────────────────────────────────────────────────────────

function dotProduct(a: number[], b: number[]): number {
  let sum = 0;
  for (let i = 0; i < a.length; i++) sum += a[i] * b[i];
  return sum;
}

function magnitude(v: number[]): number {
  return Math.sqrt(v.reduce((s, x) => s + x * x, 0));
}

function cosineSimilarity(a: number[], b: number[]): number {
  const magA = magnitude(a);
  const magB = magnitude(b);
  if (magA === 0 || magB === 0) return 0;
  return dotProduct(a, b) / (magA * magB);
}

// ── Retrieval ────────────────────────────────────────────────────────────────

export interface RetrievalResult {
  entry: Omit<EmbeddedEntry, "embedding">;
  score: number;
}

export interface RetrievalOptions {
  /** Number of results to return */
  k?: number;
  /** Filter by knowledge domain */
  domain?: KnowledgeDomain | KnowledgeDomain[];
  /** Filter by symptom system */
  symptomSystem?: SymptomSystem | SymptomSystem[];
  /** Minimum cosine similarity threshold (0–1) */
  minScore?: number;
}

/**
 * Retrieve the top-K most relevant knowledge entries for a query embedding.
 * The caller is responsible for embedding the query (via embedText()).
 */
export async function retrieveByVector(
  queryEmbedding: number[],
  options: RetrievalOptions = {}
): Promise<RetrievalResult[]> {
  const { k = 4, minScore = 0.3 } = options;
  const entries = await loadCache();

  if (entries.length === 0) return [];

  const domains = options.domain
    ? Array.isArray(options.domain) ? options.domain : [options.domain]
    : null;

  const systems = options.symptomSystem
    ? Array.isArray(options.symptomSystem) ? options.symptomSystem : [options.symptomSystem]
    : null;

  const scored = entries
    .filter((e) => {
      if (domains && !domains.includes(e.domain as KnowledgeDomain)) return false;
      if (systems && !systems.includes(e.symptomSystem as SymptomSystem)) return false;
      return true;
    })
    .map((e) => ({
      entry: {
        id: e.id,
        domain: e.domain,
        symptomSystem: e.symptomSystem,
        title: e.title,
        tags: e.tags,
        source: e.source,
        embeddedText: e.embeddedText,
      },
      score: cosineSimilarity(queryEmbedding, e.embedding),
    }))
    .filter((r) => r.score >= minScore)
    .sort((a, b) => b.score - a.score)
    .slice(0, k);

  return scored;
}

/**
 * Keyword-based fallback retrieval when embeddings are not available.
 * Uses tag matching + title keyword search (BM25-inspired scoring).
 */
export async function retrieveByKeyword(
  query: string,
  options: RetrievalOptions = {}
): Promise<RetrievalResult[]> {
  const { k = 4 } = options;
  const entries = await loadCache();

  const queryWords = query.toLowerCase().split(/\s+/).filter((w) => w.length > 2);

  const domains = options.domain
    ? Array.isArray(options.domain) ? options.domain : [options.domain]
    : null;

  const scored = entries
    .filter((e) => {
      if (domains && !domains.includes(e.domain as KnowledgeDomain)) return false;
      return true;
    })
    .map((e) => {
      const searchable = [e.title, ...e.tags, e.embeddedText].join(" ").toLowerCase();
      const matches = queryWords.filter((w) => searchable.includes(w)).length;
      const score = matches / Math.max(queryWords.length, 1);
      return {
        entry: {
          id: e.id,
          domain: e.domain,
          symptomSystem: e.symptomSystem,
          title: e.title,
          tags: e.tags,
          source: e.source,
          embeddedText: e.embeddedText,
        },
        score,
      };
    })
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, k);

  return scored;
}

/**
 * Check if retrieved results contain any emergency triage triggers.
 * Returns true if EMERGENCY_TRIAGE should be flagged.
 */
export function hasEmergencyTrigger(results: RetrievalResult[]): boolean {
  return results.some(
    (r) =>
      r.entry.symptomSystem === "emergency_triage" ||
      r.entry.domain === "emergency"
  );
}

/**
 * Format retrieved chunks into an LLM-readable context string.
 */
export function formatContextForLLM(results: RetrievalResult[]): string {
  if (results.length === 0) return "";
  return results
    .map(
      (r, i) =>
        `[Clinical Reference ${i + 1}: ${r.entry.title}]\n${r.entry.embeddedText}\nSource: ${r.entry.source}`
    )
    .join("\n\n---\n\n");
}
